version: '2'
services:
    dbtrainings-app:
        image: dbtrainings
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dbtrainings-mysql:3306/dbtrainings?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dbtrainings-mysql:
        extends:
            file: mysql.yml
            service: dbtrainings-mysql
